### ISSUE TITLE
Breakpoints hidden by green bookmark

### ISSUE THREAD

**Issue by gibberishbc** [alefragnani/vscode-numbered-bookmarks#42] opened 2018-09-28 16:02 UTC
Python 3.6 / Windows VSCode current ver / Win7

If there is a breakpoint (red circle) on the same line, the numbered bookmark will overlay the breakpoint, rendering it invisible.

Possible solutions:
(a) place the bookmark under the red breakpoint dot (downside: the edges of the green bookmark will be visible beneath the rounded red dot, BUT the number on the bookmark will be hidden)
(b) make the bookmark 1px more narrow on each side IF there is a bookmark on the same line
(c) reduce the opacity of the bookmark so the red dot is partially visible underneath

I don't know if any of these suggestions are viable, but FWIW. 
(Personal note; many thanks for your multiple contributions to making coding life easier)

**Comment by alefragnani** [comment] 2018-09-28 17:05
Hi @gibberishbc ,

First of all, thanks you. I'm glad my extensions make your life easier 👍 Feel free to [support its development](https://github.com/alefragnani/vscode-bookmarks#support-bookmarks)

About the issue, this is the same issue as https://github.com/alefragnani/vscode-bookmarks/issues/56, which is caused by a VS Code limitation, already reported in  https://github.com/Microsoft/vscode/issues/5923. No update has been made by VS Code for almost an year, so, I'm keeping my repositories clean, and closing issues that _depends on_ VS Code. 

I'm subscribed to that issue, so if/when it is closed/fixed, I'll be notified, and an update to my extensions could be made to support/fix the issues.

Hope this helps

**Closed** 2018-09-28 17:06 UTC
Labels: bug, depends on
