### ISSUE TITLE
Extension metadata is incomplete

### ISSUE THREAD

**Issue by iqapps** [alefragnani/vscode-numbered-bookmarks#174] opened 2024-06-03 09:04 UTC
I see this in the documentation for the extension.

![image](https://github.com/alefragnani/vscode-numbered-bookmarks/assets/12947531/630c3935-e3d4-421c-b537-8e4f2abcd337)

Where title is not set, and I see the same for other parts of the documentation, like details on the other pages.

**Comment by alefragnani** [comment] 2024-06-28 01:15
Hi @iqapps ,

I couldn1t reproduce this error in the latest (v8.5.0) release. 

Could you update yours and try again to see if it is fixed?

Thanks in advance

**Comment by alefragnani** [comment] 2024-09-06 02:59
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Closed by alefragnani** 2024-09-06 02:59 UTC
Labels: bug, need more info
