### ISSUE TITLE
Bookmark icons are missing

### ISSUE THREAD

**Issue by brentonhouse** [alefragnani/vscode-numbered-bookmarks#15] opened 2016-12-01 19:58 UTC
The bookmarks function properly but there is no indicator.  Using version 1.7.2 on OS X.

**Comment by alefragnani** [comment] 2016-12-01 23:29
Hi @brentonhouse ,

It seems the same issue reported sometime ago (#31), caused by a bug in VSCode. It should be fixed now, at least in version 0.4.2 of the extension.

Are your extension updated?

**Closed** 2017-04-25 01:09 UTC
Labels: bug
