### ISSUE TITLE
[FEATURE] - Publish to open-vsx

### ISSUE THREAD

**Issue by misantroop** [alefragnani/vscode-numbered-bookmarks#147] opened 2022-08-01 15:38 UTC
I've installed it in one instance of VSCodium and it works great, now wanting to do the same in another machine, the extension is not found in the in-app marketplace. Even if I use the Ctrl+P method, it doesn't show up. Downloading and installing of the VSIX manually works.

**Comment by alefragnani** [comment] 2022-08-01 20:22
Hi @misantroop ,

Yes, the extension is not available at Open VSX, which is the alternative marketplace used by VSCodium. I'm planning to do so, but no ETA yet. 

I'll leave this issue open, as is a good way to measure the number of users interested.

Thanks for reporting

**Comment by mmahmoudian** [comment] 2022-08-02 08:07
I just came to open an issue for this that I found this thread. The [Bookmarks](https://github.com/alefragnani/vscode-bookmarks) is there, but this project is not. Would be great if we can have this there as well. Thanks :+1:

**Comment by Trikenstein** [comment] 2023-04-16 18:38
Hi @alefragnani you closed my feature request #160 as duplicate of this one. Came here to add my vote to have this `numbered-bookmarks` extension available for VSCodium. Thanks

**Comment by alefragnani** [comment] 2024-03-22 02:37
Just claimed the namespace https://github.com/EclipseFdn/open-vsx.org/issues/2445

**Comment by alefragnani** [comment] 2024-04-03 23:56
The namespace claim was assigned. Ready to publish.

**Comment by alefragnani** [comment] 2024-04-05 00:44
Hi,

I just published the new [release 8.5.0.](https://github.com/alefragnani/vscode-numbered-bookmarks/milestone/26) to Open VSX.

Thank you for your patience.

**Closed by alefragnani** 2024-04-05 00:44 UTC
Labels: enhancement, vscode alternative

**Comment by Trikenstein** [comment] 2024-04-06 15:13
Such an intelligent extension. Thank you very much sir. Finally I can you bookmark on VSCodium without efforts.
