### ISSUE TITLE
crashes in background

### ISSUE THREAD

**Issue by ivanstefanov** [alefragnani/vscode-numbered-bookmarks#24] opened 2017-05-03 08:50 UTC
Visual Studio Code version 1.11.2

Illegal value for `line`: Error: Illegal value for `line`
    at t._lineAt (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:242822)
    at Object.lineAt (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:241612)
    at stickyBookmarks (C:\Users\..\.vscode\extensions\alefragnani.numbered-bookmarks-0.9.0\out\extension.js:742:87)
    at C:\Users\..\.vscode\extensions\alefragnani.numbered-bookmarks-0.9.0\out\extension.js:189:35
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:16423)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:20054)
    at t.$acceptModelChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:308374)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:277319)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:135077)
    at h (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:135754)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

e.onUnexpectedError	@	/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29

**Comment by alefragnani** [comment] 2017-05-03 15:52
Hi @ivanstefanov ,

Could you tell me how to reproduce this error? I tried to do, based on the call stack (appears to be handing `Edit / Paste`, with no success. 

Thanks

**Comment by ivanstefanov** [comment] 2017-05-04 13:33
Hello, I don't know how this is happening. It just crashes sometimes. While I work with the editor, a bar with a red button appears at the top, which tells me an extension has been crashed and the window needs reload. When I checked where is the error, I saw the text, pasted above

**Comment by alefragnani** [comment] 2017-05-04 16:19
Thanks, I will try some other scenarios. 

It appears to be something related to `Copy / Paste`, because when it happens, the bookmarks needs to be _moved_. 

Let me know if you discover something new.

**Comment by alefragnani** [comment] 2018-03-08 02:38
Hi @ivanstefanov 

Do you still see this crashes? 

I was debugging the extension for another feature, and noted #35 . Then, I remembered your issue, that I never reproduced 😢 

Thanks

**Comment by ivanstefanov** [comment] 2018-03-08 09:52
Hello @alefragnani , I haven't seen such crashes from a long time. Still I am not sure what was the reason

**Comment by alefragnani** [comment] 2018-03-08 10:59
That's great to hear! 🎉 
I'm closing the issue by now. If you see it again, please, fill free to open/reopen, so I could take a look again.

Thanks

**Closed by alefragnani** 2018-03-08 10:59 UTC
Labels: bug, need more info
